[versions]
minecraft = "1.19.4"
yarn_mappings = "1.19.4+build.2"
fabric_loader = "0.15.7"
loom = "1.5-SNAPSHOT"
vineflower = "1.10.0-SNAPSHOT"
mixin_squared = "0.1.2-beta.4"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn_mappings = { module = "net.fabricmc:yarn", version.ref = "yarn_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }
mixin_squared = { module = "com.github.bawnorton.mixinsquared:mixinsquared-fabric", version.ref = "mixin_squared" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "loom" }
